export const DISPLAY_SUBSCRIPTIONS = "DISPLAY_SUBSCRIPTIONS";
export const DISPLAY_ALL_PROMOS = "DISPLAY_ALL_PROMOS";
export const DISPLAY_USER = "DISPLAY_USER";
export const STATUS_LIMIT = "STATUS_LIMIT";
